name: Force Release PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - release

jobs:
  force-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.event.pull_request.head.ref == 'main'

    steps:
      - uses: actions/checkout@v6

      - name: Generate PR description
        id: gen
        uses: tanmay-pathak/generate-pull-request-description@v1.0.0
        with:
          pull_request_url: ${{ github.event.pull_request.url }}
          api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Force overwrite PR title and body
        uses: actions/github-script@v8
        env:
          PR_BODY: ${{ steps.gen.outputs.pull_request_description }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const now = new Date().toISOString().slice(0,16).replace('T',' ');
            const body = process.env.PR_BODY;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: `Release PR for ${now}`,
              body: body
            });
